import express from 'express';
import GETUSER from '../../controller/user/sing-in/route';
import validateToken from '../../middleware/auth/verifyToken';
import RENEWTOKEN from '../../controller/user/renew-token/route';
import UPDATEPORFILE from '../../controller/user/update/profile/route';
import upload from '../../util/multer';
const router = express.Router();
router.post('/sign-in', GETUSER);
router.post('/renew-token',validateToken, RENEWTOKEN);
router.put('/update-profile', validateToken, upload.single('profile'), UPDATEPORFILE);
export default router;